// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdksnfthcvwqgzrbxgwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpka3NuZnRoY3Z3cWd6cmJ4Z3dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NDg3NTIsImV4cCI6MjA3MDMyNDc1Mn0.MvdnG4aqLXjxfpf9qXZ0MdkI9vKsCgaMoK46yPSkrx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});